---
name: Pull, scan, and push Supabase images
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * 0'  # Weekly on Sunday at 5 AM UTC

jobs:
  pull-scan-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write
    env:
      GH_REPO: gsa-tts/cg-supabase
    strategy:
      fail-fast: false
      matrix:
        platform: [linux/amd64, linux/arm64]
        image:
          # Core Supabase services (matching docker-compose.yml versions)
          - name: supabase/studio:2025.06.30-sha-6f5982d
            short-name: studio
            scan: true
          - name: kong:2.8.1
            short-name: kong
            scan: true
          - name: supabase/gotrue:v2.177.0
            short-name: auth
            scan: true
          - name: postgrest/postgrest:v12.2.12
            short-name: rest
            scan: true
          - name: supabase/realtime:v2.34.47
            short-name: realtime
            scan: true
          - name: supabase/storage-api:v1.25.7
            short-name: storage
            scan: true
          - name: darthsim/imgproxy:v3.8.0
            short-name: imgproxy
            scan: true
          - name: supabase/postgres-meta:v0.91.0
            short-name: meta
            scan: true
          - name: supabase/edge-runtime:v1.67.4
            short-name: functions
            scan: true
          - name: supabase/logflare:1.14.2
            short-name: analytics
            scan: true
          - name: supabase/postgres:15.8.1.060
            short-name: postgres
            scan: true
          - name: timberio/vector:0.28.1-alpine
            short-name: vector
            scan: true
          - name: supabase/supavisor:2.5.7
            short-name: pooler
            scan: true
          - name: inbucket/inbucket:3.0.3
            short-name: mail
            scan: true

    name: Process ${{ matrix.image.short-name }} on ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ matrix.platform }}

      - name: Pull Docker Image
        if: matrix.image.scan == true
        run: docker pull ${{ matrix.image.name }}

      - name: Scan Image
        if: matrix.image.scan == true
        uses: aquasecurity/trivy-action@0.33.0
        with:
          scan-type: 'image'
          image-ref: ${{ matrix.image.name }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          exit-code: 0
          scanners: 'vuln'

      - name: Upload Trivy scan results to GitHub Security tab
        if: ${{ !cancelled() && matrix.image.scan == true }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Tag Image
        if: matrix.image.scan == true
        run: |
          date=$(date +%Y%m%d)
          docker tag ${{ matrix.image.name }} ghcr.io/${{ env.GH_REPO }}/${{ matrix.image.short-name }}:latest
          docker tag ${{ matrix.image.name }} ghcr.io/${{ env.GH_REPO }}/${{ matrix.image.short-name }}:scanned
          docker tag ${{ matrix.image.name }} ghcr.io/${{ env.GH_REPO }}/${{ matrix.image.short-name }}:$date

      - name: Login to GitHub Container Registry
        if: matrix.image.scan == true
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Image
        if: matrix.image.scan == true
        run: docker push --all-tags ghcr.io/${{ env.GH_REPO }}/${{ matrix.image.short-name }}
